# pylint: disable=no-member,invalid-name,missing-function-docstring,too-many-statements
"""alter projects_data and create projects_territory_data

Revision ID: 7ae4ad3c1770
Revises: a2862d4a7f8b
Create Date: 2024-07-03 10:29:01.165813

"""
from typing import Sequence, Union

import geoalchemy2
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7ae4ad3c1770"
down_revision: Union[str, None] = "a2862d4a7f8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.schema.CreateSequence(sa.Sequence("project_territory_id_seq")))
    op.create_table(
        "projects_territory_data",
        sa.Column(
            "project_territory_id",
            sa.Integer(),
            server_default=sa.text("nextval('project_territory_id_seq')"),
            nullable=False,
        ),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                spatial_index=False, from_text="ST_GeomFromEWKT", name="geometry", nullable=False
            ),
            nullable=False,
        ),
        sa.Column(
            "centre_point",
            geoalchemy2.types.Geometry(
                geometry_type="POINT", spatial_index=False, from_text="ST_GeomFromEWKT", name="geometry", nullable=False
            ),
            nullable=False,
        ),
        sa.Column(
            "properties", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["user_projects_unmanaged.projects_territory_data.project_territory_id"],
            name=op.f("projects_territory_data_fk_parent_id__projects_territory_data"),
        ),
        sa.PrimaryKeyConstraint("project_territory_id", name=op.f("projects_territory_data_pk")),
        schema="user_projects_unmanaged",
    )
    op.drop_column("projects_data", "geometry", schema="user_projects_unmanaged")
    op.add_column(
        "projects_data",
        sa.Column("project_territory_id", sa.Integer(), nullable=False),
        schema="user_projects_unmanaged"
    )
    op.add_column(
        "projects_data",
        sa.Column("description", sa.String(length=600), nullable=True),
        schema="user_projects_unmanaged"
    )
    op.add_column(
        "projects_data",
        sa.Column("public", sa.Boolean(), nullable=False),
        schema="user_projects_unmanaged"
    )
    op.add_column(
        "projects_data",
        sa.Column("image_url", sa.String(length=200), nullable=True),
        schema="user_projects_unmanaged"
    )
    op.add_column(
        "projects_data",
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        schema="user_projects_unmanaged",
    )
    op.add_column(
        "projects_data",
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        schema="user_projects_unmanaged",
    )
    op.create_foreign_key(
        "projects_data_fk_project_territory_id__projects_territory_data",
        "projects_data",
        "projects_territory_data",
        ["project_territory_id"],
        ["project_territory_id"],
        source_schema="user_projects_unmanaged",
        referent_schema="user_projects_unmanaged"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "projects_data_fk_project_territory_id__projects_territory_data",
        "projects_data",
        schema="user_projects_unmanaged",
        type_="foreignkey"
    )
    op.drop_column("projects_data", "created_at", schema="user_projects_unmanaged")
    op.drop_column("projects_data", "updated_at", schema="user_projects_unmanaged")
    op.drop_column("projects_data", "image_url", schema="user_projects_unmanaged")
    op.drop_column("projects_data", "public", schema="user_projects_unmanaged")
    op.drop_column("projects_data", "description", schema="user_projects_unmanaged")
    op.drop_column("projects_data", "project_territory_id", schema="user_projects_unmanaged")
    op.add_column(
        "projects_data",
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(spatial_index=False, from_text="ST_GeomFromEWKT", name="geometry", nullable=False),
            nullable=False,
        ),
        schema="user_projects_unmanaged"
    )
    op.drop_table("projects_territory_data", schema="user_projects_unmanaged")
    op.execute(sa.schema.DropSequence(sa.Sequence("project_territory_id_seq")))
    # ### end Alembic commands ###
